<?php
/**
 * Class User
 * @property string $name
 * @property string $surname
 *
 */
class User extends FileData { //dziedziczy po filedata
	protected $fillable = [
		"name",
		"surname",
		"email",
		"password",
	]; // przeciaza pola dozwolone ktore moga byc ustawione jak publiczne atrybuty

	public function __construct( $userName ) { // ustawienie w jakim pliku przechowujemy dane
		parent::__construct( "data/users/{$userName}.dat" );
	}

	public static function userExists( $userName ) {
		return parent::fileExists( "data/users/{$userName}.dat" ); // TODO: Change the autogenerated stub
	}

	public function __set( $varname, $value
	) { // przeciazenie settera magicznego tak aby dla wyjatkowej sytuacji pola email dokonal walidacji
		switch ( $varname ) {
			case 'email':
				if ( ! filter_var( $value, FILTER_VALIDATE_EMAIL ) ) { // walidacja adresu email
					throw new Exception( "Not a valid email" );
				}
				break;
		}
		parent::__set( $varname, $value ); // wywowlanie funkcji nadrzednej jesli nie wystapi wyjatek aby sie wykonal setter
	}
}